name: producer
language: Python
variables:
  - name: OUTPUT_TOPIC
    inputType: OutputTopic
    defaultValue: stocks
  - name: output
    inputType: OutputTopic
    defaultValue: stocks
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
